services:
  traefik:
    image: traefik:v3.4.0
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=gourav@nazrein.dev"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - frontend

  user:
    image: grvbrk/nazrein:user-${GIT_COMMIT_HASH:-latest}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.user.loadbalancer.server.port=3000"
      - "traefik.http.routers.user.rule=Host(`nazrein.dev`)"
      - "traefik.http.routers.user.entrypoints=websecure"
      - "traefik.http.routers.user.tls.certresolver=myresolver"
    secrets:
      - doppler_token
    environment:
      DOPPLER_TOKEN: /run/secrets/doppler_token
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3000/"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    networks:
      - frontend
      - backend

  admin:
    image: grvbrk/nazrein:admin-${GIT_COMMIT_HASH:-latest}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.admin.loadbalancer.server.port=3001"
      - "traefik.http.routers.admin.rule=Host(`admin.nazrein.dev`)"
      - "traefik.http.routers.admin.entrypoints=websecure"
      - "traefik.http.routers.admin.tls.certresolver=myresolver"
    secrets:
      - doppler_token
    environment:
      DOPPLER_TOKEN: /run/secrets/doppler_token
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3001/"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    networks:
      - frontend
      - backend

  server:
    image: grvbrk/nazrein:server-${GIT_COMMIT_HASH:-latest}
    secrets:
      - doppler_token
    environment:
      DOPPLER_TOKEN: /run/secrets/doppler_token
    networks:
      - backend

  publisher:
    image: grvbrk/nazrein:publisher-${GIT_COMMIT_HASH:-latest}
    secrets:
      - doppler_token
    environment:
      DOPPLER_TOKEN: /run/secrets/doppler_token
    networks:
      - backend

  worker:
    image: grvbrk/nazrein:worker-${GIT_COMMIT_HASH:-latest}
    secrets:
      - doppler_token
    environment:
      DOPPLER_TOKEN: /run/secrets/doppler_token
    networks:
      - backend

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      # - ./config/config.xml:/etc/clickhouse-server/config.d/docker.xml
      # - ./config/users.xml:/etc/clickhouse-server/users.d/docker.xml
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: clickhouse
      CLICKHOUSE_PASSWORD: clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    # deploy:
    #   resources:
    #     limits:
    #       memory: 8G
    #     reservations:
    #       memory: 4G
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - backend

secrets:
  doppler_token:
    external: true

volumes:
  letsencrypt:
  clickhouse_data:

networks:
  frontend:
    driver: overlay
  backend:
    driver: overlay
